### ISSUE TITLE
update key frames 

### ISSUE THREAD

**Issue by qweesiic** [vectr-ucla/direct_lidar_odometry#13]
thanks for fully and quickly answering last question!
now if feature info had been changed largely after mapping ,  the accuracy and stability of  localization must be terrible. 
to avoid this situation,  exactly update key frames whose feature info has changed   should be better solution.
so as your suggestion, how to exactly update key frames whose feature info has changed ? 
thanks.

**Comment by kennyjchen** [comment]
Hi @qweesiic -- DLO currently assumes a static environment during runtime and doesn't account for dynamic changes. Empirically speaking though, we've seen promising results in the presence of dynamic objects (e.g., walking people) even without updating keyframe covariances for submap scan-matching, perhaps due to GICP's robustness to incorrect correspondences. However, keyframe covariances and map representation could probably be updated continuously after detecting an environmental change somehow, as you mentioned. Localization in dynamic environments is definitely still an active area of research.

**Comment by qweesiic** [comment]
got it! thanks.
