### ISSUE TITLE
Coordinate system conversion

### ISSUE THREAD

**Issue by HomieRegina** [vectr-ucla/direct_lidar_odometry#18]
Hi, thanks for your great work. I used my lidar and imu to record the data set and run it in DLO. The following figure is the map generated by the algorithm. I found that IMU drift is very serious. Is this related to coordinate system transformation? How can I set up and configure files to improve this situation?
![d0724d53975aa58f749b1abfa692456](https://user-images.githubusercontent.com/107244263/178234805-3e6bcc14-777e-41e4-879d-82d9fbe7fb75.jpg)
![3ae5711ad4dc74f03c683af98bc7db9](https://user-images.githubusercontent.com/107244263/178234880-de047897-17a4-4b79-915a-abcb50c8eed3.jpg)

**Comment by HomieRegina** [comment]
Add something. When my coordinate system is velodyne and the topic is changed to /robot/dlo/map_node/map, it is empty on rviz. When my coordinate system is changed to robot/odom, nothing is displayed on rviz.

**Comment by kennyjchen** [comment]
Looks like an extrinsics issue if I had to guess.

Does it work if IMU is disabled by setting [`imu: false`](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/dlo.yaml#L16)? If so, then your IMU is probably flipped and providing DLO with a wrong scan-matching prior. The current implementation assumes that the LiDAR and IMU coordinate frames coincide, so if it's possible try rearranging your sensors to ROS convention (forward-left-up). Otherwise I can add support for extrinsics.

**Comment by kennyjchen** [comment]
Does it work if IMU is disabled by setting [`imu: false`](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/dlo.yaml#L16)? If so, then your IMU is probably flipped and providing DLO with a wrong scan-matching prior. The current implementation assumes that the LiDAR and IMU coordinate systems coincide, so try rearranging your sensors to align (preferably in ROS forward-left-up) if possible. Otherwise I can add support for extrinsics.

**Comment by HomieRegina** [comment]
Thank you for your reply. When imu is disabled by setting, its map has not changed. I checked the defined lidar coordinate system and the defined IMU coordinate system. They are coincident. But I found that my lidar and imu still drifted seriously. The following two figures are the coordinate system of lidar and imu. Do I need to recalibrate the lidar and imu?

![image](https://user-images.githubusercontent.com/107244263/178452100-19c1e2f9-fe2c-45f4-b6ce-0b1ddf028b15.png)

![image](https://user-images.githubusercontent.com/107244263/178452200-396dd65d-10f1-44fe-9e27-e107fa9953c8.png)

**Comment by kennyjchen** [comment]
Hmm... which sensors are you using? There was a similar issue [a while ago](https://github.com/vectr-ucla/direct_lidar_odometry/issues/4) which was fixed through some configuration. Otherwise if you record a bag for me I can help debug.

**Comment by kennyjchen** [comment]
Hmm... which sensors are you using? There was a similar issue [a while back](https://github.com/vectr-ucla/direct_lidar_odometry/issues/4) which was fixed through a configuration change, so try checking your driver settings. Otherwise if you record a bag for me I can help debug.

**Comment by HomieRegina** [comment]
Well, thank you for your reply and I have solved some issues. The data set with serious drift before recorded all topics of IMU and lidar. When I recorded the topic of using only IMU acceleration data and lidar pointcloud data in the data set, the drift situation was basically solved. Could you please tell me whether the motion trajectory, attitude and other sensor information of IMU will affect the accuracy of mapping? 

When the lidar system moves unsteadily on the carrier, the built map will have errors in the horizontal direction. As shown in the following figure. But this problem does not exist on the stable moving carrier. Here is [the data set](https://t.wss.ink/f/8seo9q7he0d ).Do I need to calibrate the random error of IMU?
![image](https://user-images.githubusercontent.com/107244263/178676401-7a22b260-6c1c-4d34-a901-773039e56f55.png)
By the way, is there any setting for the joint calibration of the coordinate system of lidar and IMU in the program?

**Comment by kennyjchen** [comment]
Interesting. It shouldn't; the [IMU callback](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/odom.cc#L708) only pulls from the [`angular_velocity`](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/odom.cc#L717-L719) and [`linear_acceleration`](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/odom.cc#L721-L723) fields. Glad to hear you figured it out though.

DLO's world coordinate system depends on the initial position of the LiDAR, so if you start tilted the entire map will be tilted. I checked out your bag though and it looks like you disabled [gravity alignment](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/dlo.yaml#L17). Your data does better if you turn it on. Keep in mind that the gravity vector isn't fully observable (strictly speaking) so it's just an estimated procedure -- but we've seen pretty good results from our experience (with a good IMU).

Extrinsics isn't currently supported, but it's not as necessary as other approaches since we're just using a [relative rotational prior](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/odom.cc#L807) for scan-matching.

**Comment by HomieRegina** [comment]
Thank you for your reply and patience. I have solved the above problems.
By the way. How to generate .pcd format file? I use the official order to get the following information.
![图片](https://user-images.githubusercontent.com/107244263/178959432-440f0cbf-d8f6-42b1-bec6-6223963f3c07.png)

**Comment by kennyjchen** [comment]
Happy to help. You need a space between the two arguments, and the last argument should be the parent folder for the file, i.e.

```
rosservice call /robot/dlo_map/save_pcd 0.5 ~/Downloads
```

will save the map as `~/Downloads/dlo_map.pcd`.

**Comment by HomieRegina** [comment]
Thanks for your great work and attentive reply. I have successfully got the .pcd file. 

Now I found new problems. Here are some pictures that are the results of the data set I recorded in the outdoor environment. In Figure 2, it can be seen from the .pcd file that there is an obvious drift in the map. When the path of motion returns to the origin, you can clearly see the drift of the map (as shown in Figure 3). Have you ever encountered this situation when you were building a map? How did you solve it?

By the way, there are obvious pause (not jitter) when building the map. What is the reason for this?

![图片](https://user-images.githubusercontent.com/107244263/179134707-c059ce31-387b-467c-b87f-f911e8f88d2c.png)
![图片](https://user-images.githubusercontent.com/107244263/179165960-9bdeb44a-921c-485d-95b7-6d75fe5dc59a.png)
![图片](https://user-images.githubusercontent.com/107244263/179135003-fddcbe6e-6e9b-4d40-8fd2-24cf7b9e0929.png)

**Comment by kennyjchen** [comment]
I don't see any obvious drift with your map itself, but if you are referring to the map's tilt, make sure you start on flat ground as I mentioned previously (i.e., Z is axis-aligned to gravity). If you're using our gravity alignment procedure, the IMU and LiDAR needs to be rotationally-aligned on your platform (I can't tell if they are from your second reply).

Regarding the periodic pauses, our map publisher is on a one second [`ros::Timer`](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/map.cc#L102), so RViz may slow down / delay as the map grows. This was done in the event of lost communication with our robots for SubT so that the robot could send the full map once it came within range again. I added an [option](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/dlo.yaml#L24) in [`v1.4.2`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.2) to turn this off and only publish keyframes individually as a solution. Make sure to turn up the [Decay Time](http://wiki.ros.org/rviz/DisplayTypes/PointCloud) if you want to see the full map.

**Comment by kennyjchen** [comment]
I don't see any obvious drift with your map itself, but if you are referring to the map's tilt, make sure you start on flat ground as I mentioned previously (i.e., Z is axis-aligned to gravity). Your initial position looks like it has some positive roll and maybe some negative pitch. If you're using our gravity alignment procedure, the IMU and LiDAR needs to be rotationally-aligned on your platform (I can't tell if they are from your second reply).

Regarding the periodic pauses, our map publisher is on a one second [`ros::Timer`](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/map.cc#L102), so RViz may slow down / delay as the map grows. This was done in the event of lost communication with our robots for SubT so that the robot could send the full map once it came within range again. I added an [option](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/dlo.yaml#L24) in [`v1.4.2`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.2) to turn this off and only publish keyframes individually as a solution. Make sure to turn up the [Decay Time](http://wiki.ros.org/rviz/DisplayTypes/PointCloud) if you want to see the full map.

**Comment by HomieRegina** [comment]
Thank you for your patient reply. I think maybe my statement is not accurate enough. You can pay close attention to my latest reply (the reply with three photos) because this data set is a new recording package. My data set starts from the starting point and finally returns to the starting point. You could see in my last picture that there is a height difference between my starting position and my final position.  This height difference is the problem I want to solve. Do you know the reason for the inaccurate vertical positioning? 
And I'm sure I set [gravityAlign:true](cfg/dlo.yaml) and the IMU and lidar coordinate system are physically consistent, but there is no rotation alignment. Do I need to rotate and align the IMU and lidar? How to achieve rotation alignment? Can rotating alignment solve the problem of inaccurate vertical positioning? We look forward to your reply.

**Comment by kennyjchen** [comment]
Try playing around with the voxelization (i.e, turn off [submap voxelization](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/params.yaml#L35)), the number of [keyframes](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/params.yaml#L44-L45) used in submapping (maybe increase it), and the maximum correspondence distances for [S2S](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/params.yaml#L35) and [S2M](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/cfg/params.yaml#L65).

**Comment by HomieRegina** [comment]
Hi, thank you for your good work and reply. I'm trying to adjust these parameters these days. I want to ask you something I'm not very clear about. 

When I changed the parameters of submap voxeFilter, I found that the clarity of its mapping has changed. When I looked at the code, I found that this parameter is related to the keyframe of the point cloud. Is that right? But when I turned down this parameter, I found that the mapping was clearer. When I turned up this parameter, I found that the number of keyframes become less. So I want to ask, is this parameter a filter? Does it take the reciprocal when used? Or in other forms?

And when I adjusted the parameter of maximum correspondence distances, I knew nothing about the changes in the mapping process. But it is clear that the coordinate error of the map has changed a lot. I can't find its rule for the time being. I want to know what factors affect the mapping process by adjusting the maximum correspondence distances parameters of S2S and S2M in GICP. 

Thank you for your answer. We look forward to your reply

**Comment by kennyjchen** [comment]
A voxel filter downsamples a pointcloud depending on the [leaf size](https://pointclouds.org/documentation/classpcl_1_1_voxel_grid_3_01pcl_1_1_p_c_l_point_cloud2_01_4.html#ad3efe8cb07386b291c88c5178e8b135d) of each voxel. Think of this as the size of each "3D pixel," so the larger the number the bigger the voxel and vice versa. Then, for a leaf size of 0.1 (for example), there will be one point per 0.1 cubic meters in the cloud.

This can affect DLO's adaptive keyframing from our [spaciousness](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/src/dlo/odom.cc#L994) metric, which computes the median point distance. 

Maximum correspondence distance affects scan-matching and which pair of points to consider during optimization. In larger environments, a larger distance is generally good since points are probably more spread out. In smaller environments (like your dataset), bad correspondence matching can corrupt the optimization process and therefore the overall result. This holds true mainly for S2M; for S2S, the search is purely between two instantaneous scans. In that case, it's slightly dependent on walking speed and the rate of the LiDAR (but in general it's not as sensitive as S2M).

[Here](https://pointclouds.org/documentation/tutorials/voxel_grid.html) is a nice tutorial on what voxel filtering is, and you can read more [here](https://en.wikipedia.org/wiki/Point-set_registration#Correspondence-based_registration) about correspondence-based registration.

**Comment by HomieRegina** [comment]
Thanks for your reply. I will understand this part carefully. 

I recorded a dataset in the business district and built a map. We took the escalator from the second floor of the mall to the first floor of the mall. After turning around on the first floor, I returned to the starting point of the second floor. The effect of the map is good. 
![image](https://user-images.githubusercontent.com/107244263/180343368-ae0e8cfb-e966-46b2-9b4f-76a7626874b5.png)
![image](https://user-images.githubusercontent.com/107244263/180343404-7ff2cc03-626d-421a-9838-9e29201e52e5.png)
![image](https://user-images.githubusercontent.com/107244263/180353758-73558089-bc59-4adf-878e-585da33ab16b.png)
![image](https://user-images.githubusercontent.com/107244263/180343428-5ace972c-407c-4b08-abe8-38829c5b7c7e.png)
You can see a slash across the second floor. Don't worry. This part is the escalator from the second floor to the third floor. As shown in the third figure.

**Comment by kennyjchen** [comment]
Nice! Thanks for sharing your results with us :^)

If there are no more questions, I'll be closing this thread. Feel free to reopen or create a new issue if you have any further questions or comments about our work.
