### ISSUE TITLE
Conversion of lidar and IMU coordinate system

### ISSUE THREAD

**Issue by HomieRegina** [vectr-ucla/direct_lidar_odometry#21]
Hi! I use a vlp16 lidar and a microstran imu(3DM-GX5-25) to record bags. And here is the part of the map I built with your algorithm. Because the coordinate systems of IMU and lidar are not consistent in the physical direction, this has affected the construction of the two-layer environment. Could you please tell me how to convert IMU and lidar coordinate system?
![图片](https://user-images.githubusercontent.com/107244263/185014739-46e84f0b-fc5d-4088-ab98-9708a94eead1.png)

**Comment by kennyjchen** [comment]
DLO currently assumes that IMU and LiDAR coordinate systems roughly coincide. I may add support for extrinsics into DLO in the future, but for now try mounting your IMU upside-down so that it points forward-left-up (ROS convention) if possible. It's a bit hacky but it should work.

That being said, can you point out the issue in your map? It's a little hard to tell what is going on since all points are colored red. Thanks.

**Comment by HomieRegina** [comment]
Thank you for your reply. I will try your method again. 
About your question: this picture is the part of the map I built. The picture below is the whole map. This is the result of adjusting the parameters. The map is tilted as a whole. But the two floors are relatively parallel.  Do you have any good adjustment suggestions for this situation?
![图片](https://user-images.githubusercontent.com/107244263/185276334-2ed564ed-60e7-4c34-8141-8a66a0e6491b.png)

**Comment by kennyjchen** [comment]
If the floors are relatively parallel (which they look like they are), but the whole map is tilted, it could be a bad initial position as we discussed [here](https://github.com/vectr-ucla/direct_lidar_odometry/issues/18). Try starting from a level surface.

**Comment by HomieRegina** [comment]
Thank you for your reply and I will try again. Thanks for your good job and patience.
