### ISSUE TITLE
large drift in z-axis

### ISSUE THREAD

**Issue by WeilongXia** [vectr-ucla/direct_lidar_odometry#34]
Thanks a lot for open sourcing such a great work! But I found during the experiment that the odometry drifts a lot in the z-axis estimation. I walked about 600m with the Lidar in hand, and when I returned to the starting point, I could see that the created point cloud map would gradually become warped. Is there any good way to solve it, such as parameter adjustment or exercise mode change? The Lidar I use is Livox MID360. Looking forward to hearing from you.
![Screenshot from 2023-06-16 16-25-34](https://github.com/vectr-ucla/direct_lidar_odometry/assets/61641798/79ab6f5e-ffb1-4574-86f2-25d71d9a901a)
![Screenshot from 2023-06-16 16-15-48](https://github.com/vectr-ucla/direct_lidar_odometry/assets/61641798/584a2de9-8ee6-4093-97b2-777e2c973125)

**Comment by kennyjchen** [comment]
Hi @WeilongXia -- check out [this issue](https://github.com/vectr-ucla/direct_lidar_odometry/issues/18).

If you are not using gravity alignment, DLO's reference frame depends on its initial orientation (so if the initial orientation is tilted, the entire map will be tilted). Try starting DLO with your sensor on a flat surface. If you are using gravity alignment, make sure your LiDAR and IMU are horizontally-aligned otherwise it will not work (and that your IMU is sufficiently high-quality). Let me know if that helps.

**Comment by WeilongXia** [comment]
Hi, I have tried placing the Lidar horizontally when the program is on, and the effect has been greatly improved! Thanks for you help!
![Screenshot from 2023-06-16 17-13-53](https://github.com/vectr-ucla/direct_lidar_odometry/assets/61641798/986989cf-6c9c-4998-a64d-42331342b86f)
![Screenshot from 2023-06-16 17-13-05](https://github.com/vectr-ucla/direct_lidar_odometry/assets/61641798/873daafb-a2cf-4a0e-b9cf-4a4b3c27659f)
