### ISSUE TITLE
How to improve the publish frequency of odom?

### ISSUE THREAD

**Issue by Joosoo1** [vectr-ucla/direct_lidar_odometry#36]
Hello great author, the point cloud publish frequency of my lidar is 10hz, at this time the frequency of odom output from DLO is also 10hz, is there any way to increase the publish frequency of odom, I have some work that needs high frequency pose estimation.thanks！

**Comment by Joosoo1** [comment]
This is a very good job, thank you very much for making it open source!

**Comment by kennyjchen** [comment]
Since DLO is LiDAR-only, the update rate is limited by how fast new measurements are received. You could artificially increase the pose estimate by putting the publisher on a ros::Timer, but that will just republish the same pose multiple times until a new update comes in.

You can try using DLIO (I see that you are already), so that the IMU helps with faster state estimation.

**Comment by Joosoo1** [comment]
Okay, I get it, thanks your reply! i will closed this issue.
